name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Enable web support
      run: flutter config --enable-web
      working-directory: miniapp_crypto_deskoin

    - name: Get dependencies
      run: flutter pub get
      working-directory: miniapp_crypto_deskoin

    - name: Build web
      run: flutter build web --release --base-href=/miniapp_crypto_deskoin/
      working-directory: miniapp_crypto_deskoin

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: miniapp_crypto_deskoin/build/web
